In [24]:
import numpy as np
import pandas as pd

In [25]:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
    for c in cols}
    return pd.DataFrame(data, ind)

In [26]:
make_df('ABC', range(3))

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

# pd.concat
Pandas concatenation preserves indices, even if the result will have duplicate indices!

### simple concatenation of Series

In [27]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])

In [28]:
ser1

1    A
2    B
3    C
dtype: object

In [29]:
ser2

4    D
5    E
6    F
dtype: object

In [30]:
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

### concatenation of dataframes
By default, the concatenation takes place row-wise within the DataFrame

In [31]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])

In [32]:
df1

    A   B
1  A1  B1
2  A2  B2

In [33]:
df2

    A   B
3  A3  B3
4  A4  B4

In [34]:
pd.concat([df1, df2])

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

pd.concat allows specification of an axis along which concatenation will take place. Consider the following example

In [35]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])

In [36]:
df3

    A   B
0  A0  B0
1  A1  B1

In [37]:
df4

    C   D
0  C0  D0
1  C1  D1

In [38]:
pd.concat([df3, df4], axis=1)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

### Ignoring the dupliccate index
Sometimes the index itself does not matter, and you would prefer it to simply be ignored. You can specify this option using the ignore_index flag. With this set to True, the concatenation will create a new integer index for the resulting Series

In [39]:
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])

In [40]:
print(x)
print(y)

    A   B
0  A0  B0
1  A1  B1
    A   B
2  A2  B2
3  A3  B3

In [41]:
x.index = y.index

In [42]:
pd.concat([x, y], ignore_index=True)

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

## Concatenation with Joins
In the simple examples we just looked at, we were mainly concatenating DataFrames with shared column names. In practice, data from different sources might have different sets of column names, and pd.concat offers several options in this case. Consider the concatenation of the following two DataFrames, which have some (but not all!) columns in common

In [43]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])

In [44]:
df5

    A   B   C
1  A1  B1  C1
2  A2  B2  C2

In [45]:
df6

    B   C   D
3  B3  C3  D3
4  B4  C4  D4

In [47]:
pd.concat([df5, df6], join="inner")

    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4