In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [6]:
planets = sns.load_dataset("planets")
planets.sample(5)

              method  number  orbital_period   mass  distance  year
858          Transit       2       11.776000    NaN       NaN  2013
433  Radial Velocity       1      835.477000  11.09     97.66  2009
966          Transit       1        8.158715    NaN     87.00  2010
981          Transit       1        3.764825    NaN       NaN  2010
577          Imaging       1             NaN    NaN     40.85  2006

In [7]:
planets.shape

(1035, 6)

# Simple aggregation in Pandas

In [8]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.rand(5))
ser

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64

In [10]:
print(ser.sum())
print(ser.mean())
print(ser.median())

2.811925491708157
0.5623850983416314
0.5986584841970366

### Aggregation on dataframes
For a DataFrame, by default the aggregates return results within each column

In [13]:
df = pd.DataFrame({'A': rng.rand(5),
                   'B': rng.rand(5)})
df

          A         B
0  0.785176  0.607545
1  0.199674  0.170524
2  0.514234  0.065052
3  0.592415  0.948886
4  0.046450  0.965632

In [14]:
print(df.mean())

A    0.427590
B    0.551528
dtype: float64

In [15]:
# By specifying the axis argument, you can instead aggregate within each row
print(df.mean(axis='columns'))

0    0.696360
1    0.185099
2    0.289643
3    0.770650
4    0.506041
dtype: float64

In [17]:
planets.dropna().describe()

          number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

# Groupby: Split, Apply, Combine

### Split, apply, combine
##### The split step involves breaking up and grouping a DataFrame depending on the
value of the specified key.
##### The apply step involves computing some function, usually an aggregate, transformation,
or filtering, within the individual groups.
##### The combine step merges the results of these operations into an output array.